### ISSUE TITLE
Not billable efforts shown to customer

### ISSUE THREAD

**Issue by tk0e** [adfinis/customer-center#411]
Hi

After some reports got questioned by a customer I found out, that Timed positions, marked as "Not Billable" are shown in Customer Center. The efforts are not counted to the total sum of efforts. But this is not obvious to the customer.

Please make sure to not show "Not Billable" efforts to the customer.

Please also check, if CC handles position flagged with "Review needed" correctly. They should not be shown to customers either. I did not check this.

Since this causes confusion and discussions with the customer, I consider this a critical bug. Please fix asap.

Cheers, Thomas

**Comment by tk0e** [comment]
I checked with 
https://timed.adfinis.com/analysis?customer=338&notBillable=0&project=4970

Compared to https://my.adfinis.com/detail/4970

**Comment by derrabauke** [comment]
We are on it!
